/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examplelibrary.View;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLms = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblBookDetails = new javax.swing.JButton();
        lblBookReservation = new javax.swing.JButton();
        lblMemberDetails = new javax.swing.JButton();
        lblBookCategories = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLms.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLms.setText("Library Management System");

        lblWelcome.setForeground(new java.awt.Color(0, 0, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome !");

        lblBookDetails.setText("Book Details");
        lblBookDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBookDetailsActionPerformed(evt);
            }
        });

        lblBookReservation.setText("Book Reservation");
        lblBookReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBookReservationActionPerformed(evt);
            }
        });

        lblMemberDetails.setText("Member Details");
        lblMemberDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMemberDetailsActionPerformed(evt);
            }
        });

        lblBookCategories.setText("Book Categories");
        lblBookCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBookCategoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBookCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMemberDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblLms, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLms, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(lblBookCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBookReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMemberDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBookCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBookCategoriesActionPerformed
        pageBookCategories();
    }//GEN-LAST:event_lblBookCategoriesActionPerformed

    private void lblBookDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBookDetailsActionPerformed
        pageBookDetails();
    }//GEN-LAST:event_lblBookDetailsActionPerformed

    private void lblBookReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBookReservationActionPerformed
        pageBookReservation();
    }//GEN-LAST:event_lblBookReservationActionPerformed

    private void lblMemberDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMemberDetailsActionPerformed
        pageMemberDetails();
    }//GEN-LAST:event_lblMemberDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lblBookCategories;
    private javax.swing.JButton lblBookDetails;
    private javax.swing.JButton lblBookReservation;
    private javax.swing.JLabel lblLms;
    private javax.swing.JButton lblMemberDetails;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables

    private void pageBookCategories(){
        try {
            BookCategoriesView bc = new BookCategoriesView();
            bc.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }
    
    private void pageBookDetails(){
        try {
            BookDetailsView bd = new BookDetailsView();
            bd.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");

        }
    }
    
    private void pageBookReservation(){
        try {
            BookReservationView br = new BookReservationView();
            br.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }
    
    private void pageMemberDetails(){
         try {
            MemberDetailsView md = new MemberDetailsView();
            md.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }
}
